In [4]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np

plt.style.use("fivethirtyeight")

In [2]:
#!pip install joblib

  Using cached joblib-1.3.1-py3-none-any.whl (301 kB)


In [5]:
class perceptron:
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta #learning rate
        self.epochs = epochs #iterations
        
    def fit(self, x, y):
        self.x = x
        self.y = y
        x_with_bias = np.c_[self.x, -np.ones((len(self.x),1))]
        print(f"x_with_bias: \n{x_with_bias}")
        

In [7]:
obj = perceptron(eta=0.01,epochs=10)

In [8]:
obj.eta

0.01

In [9]:
obj.epochs

10

In [10]:
obj.weights

array([-8.61369088e-05, -7.81095509e-05,  8.21955365e-05])

In [14]:
x = np.ones((4,2))

In [15]:
x

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
y = -np.ones((4,1))

In [17]:
y

array([[-1.],
       [-1.],
       [-1.],
       [-1.]])

In [18]:
np.c_[x,y]

array([[ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.],
       [ 1.,  1., -1.]])

In [19]:
obj.fit(x,y)

x_with_bias: 
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]
